### ISSUE TITLE
Can it be used on Python 2.7?

### ISSUE THREAD

**Issue by pphanwang** [vgrabovets/multi_rake#28]
Can it be used on Python 2.7?

**Comment by vgrabovets** [comment]
No, it can't and support for 2.7 is not planned.

**Comment by pphanwang** [comment]
sudo python3 setup.py install

=================================
/usr/lib/python3.5/distutils/dist.py:261: UserWarning: Unknown distribution option: 'python_requires'
  warnings.warn(msg)
running install
Checking .pth file support in /usr/local/lib/python3.5/dist-packages/
/usr/bin/python3 -E -c pass
TEST PASSED: /usr/local/lib/python3.5/dist-packages/ appears to support .pth files
running bdist_egg
running egg_info
creating multi_rake.egg-info
writing dependency_links to multi_rake.egg-info/dependency_links.txt
writing multi_rake.egg-info/PKG-INFO
writing requirements to multi_rake.egg-info/requires.txt
writing top-level names to multi_rake.egg-info/top_level.txt
writing manifest file 'multi_rake.egg-info/SOURCES.txt'
reading manifest file 'multi_rake.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files matching '*.pyc' found anywhere in distribution
warning: no previously-included files matching '__pycache__' found anywhere in distribution
writing manifest file 'multi_rake.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib
creating build/lib/multi_rake
copying multi_rake/utils.py -> build/lib/multi_rake
copying multi_rake/stopwords.py -> build/lib/multi_rake
copying multi_rake/__init__.py -> build/lib/multi_rake
copying multi_rake/algorithm.py -> build/lib/multi_rake
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/multi_rake
copying build/lib/multi_rake/utils.py -> build/bdist.linux-x86_64/egg/multi_rake
copying build/lib/multi_rake/stopwords.py -> build/bdist.linux-x86_64/egg/multi_rake
copying build/lib/multi_rake/__init__.py -> build/bdist.linux-x86_64/egg/multi_rake
copying build/lib/multi_rake/algorithm.py -> build/bdist.linux-x86_64/egg/multi_rake
byte-compiling build/bdist.linux-x86_64/egg/multi_rake/utils.py to utils.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/multi_rake/stopwords.py to stopwords.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/multi_rake/__init__.py to __init__.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/multi_rake/algorithm.py to algorithm.cpython-35.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying multi_rake.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying multi_rake.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying multi_rake.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying multi_rake.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying multi_rake.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating dist
creating 'dist/multi_rake-0.0.1-py3.5.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing multi_rake-0.0.1-py3.5.egg
Removing /usr/local/lib/python3.5/dist-packages/multi_rake-0.0.1-py3.5.egg
Copying multi_rake-0.0.1-py3.5.egg to /usr/local/lib/python3.5/dist-packages
multi-rake 0.0.1 is already the active version in easy-install.pth

Installed /usr/local/lib/python3.5/dist-packages/multi_rake-0.0.1-py3.5.egg
Processing dependencies for multi-rake==0.0.1
Searching for cld2-cffi>=0.1.4
Reading https://pypi.python.org/simple/cld2-cffi/
Best match: cld2-cffi 0.1.4
Downloading https://files.pythonhosted.org/packages/52/6d/044789e730141bcda2a7368836f714684a7d13bd44a2a33b387cb31b4335/cld2-cffi-0.1.4.tar.gz#sha256=3a29948364ed1e426c5bf542832eee208b1c70c0ad512b1a99bec0e6486f6c67
Processing cld2-cffi-0.1.4.tar.gz
Writing /tmp/easy_install-c71nky1w/cld2-cffi-0.1.4/setup.cfg
Running cld2-cffi-0.1.4/setup.py -q bdist_egg --dist-dir /tmp/easy_install-c71nky1w/cld2-cffi-0.1.4/egg-dist-tmp-q0elrv7b
Package libffi was not found in the pkg-config search path.
Perhaps you should add the directory containing `libffi.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libffi' found
Package libffi was not found in the pkg-config search path.
Perhaps you should add the directory containing `libffi.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libffi' found
Package libffi was not found in the pkg-config search path.
Perhaps you should add the directory containing `libffi.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libffi' found
Package libffi was not found in the pkg-config search path.
Perhaps you should add the directory containing `libffi.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libffi' found
Package libffi was not found in the pkg-config search path.
Perhaps you should add the directory containing `libffi.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libffi' found
c/_cffi_backend.c:15:17: fatal error: ffi.h: 没有那个文件或目录
compilation terminated.
error: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

**Comment by pphanwang** [comment]
I have solved this problem, and this method can be used if you encounter this problem.
========================================
sudo apt-get install python3 python-dev python3-dev 
 sudo apt-get install   build-essential libssl-dev libffi-dev 
 sudo apt-get install  libxml2-dev libxslt1-dev zlib1g-dev 
 sudo apt-get install  python-pip
sudo python3 setup.py install
