### ISSUE TITLE
Muli-rake installation failed

### ISSUE THREAD

**Issue by MariamRiaz** [vgrabovets/multi_rake#37]
I am trying to use multirake in a google colab notebook. i keep on getting this error 
sing cached https://files.pythonhosted.org/packages/52/6d/044789e730141bcda2a7368836f714684a7d13bd44a2a33b387cb31b4335/cld2-cffi-0.1.4.tar.gz
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

i tried installing pip install cld2-cffi and it gives the error 
collecting cld2-cffi
  Using cached https://files.pythonhosted.org/packages/52/6d/044789e730141bcda2a7368836f714684a7d13bd44a2a33b387cb31b4335/cld2-cffi-0.1.4.tar.gz
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by vgrabovets** [comment]
You need to install it like this `CFLAGS="-Wno-narrowing" pip install multi-rake`

**Comment by KhaledMEB** [comment]
> You need to install it like this `CFLAGS="-Wno-narrowing" pip install multi-rake`

Works for me.

**Comment by baumkuchen42** [comment]
I have the same issue but the fix described here didn't work for me.

What did work is installing pycld2 instead of cld2 and changing the `cld2` in `utils.py` to `pycld2`.

**Comment by vgrabovets** [comment]
Switched from cld2 to pycld2, installation issues should be fixed.
