### ISSUE TITLE
pip install multi-rake give this error: Command python setup.py egg_info failed with error code 1 in /tmp/pip-install-pvx6l20l/cld2-cffi/

### ISSUE THREAD

**Issue by ZackPashkin** [vgrabovets/multi_rake#9]
**Cannot install multi-rake**
pip install multi-rake gives this error: 
Command python setup.py egg_info failed with error code 1 in /tmp/pip-install-pvx6l20l/cld2-cffi/

**environment: google colab**

`Collecting multi-rake
  Using cached https://files.pythonhosted.org/packages/5f/26/8d1fd22c5e1bf65936bae9f8201df2fa8cefe6fa0b28f471384e8101b298/multi_rake-0.0.1-py3-none-any.whl
Collecting cld2-cffi>=0.1.4 (from multi-rake)
  Using cached https://files.pythonhosted.org/packages/52/6d/044789e730141bcda2a7368836f714684a7d13bd44a2a33b387cb31b4335/cld2-cffi-0.1.4.tar.gz
**Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-pvx6l20l/cld2-cffi/**`

**Comment by koper921** [comment]
> **Cannot install multi-rake**
> pip install multi-rake gives this error:
> Command python setup.py egg_info failed with error code 1 in /tmp/pip-install-pvx6l20l/cld2-cffi/
> 
> **environment: google colab**
> 
> `Collecting multi-rake Using cached https://files.pythonhosted.org/packages/5f/26/8d1fd22c5e1bf65936bae9f8201df2fa8cefe6fa0b28f471384e8101b298/multi_rake-0.0.1-py3-none-any.whl Collecting cld2-cffi>=0.1.4 (from multi-rake) Using cached https://files.pythonhosted.org/packages/52/6d/044789e730141bcda2a7368836f714684a7d13bd44a2a33b387cb31b4335/cld2-cffi-0.1.4.tar.gz **Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-pvx6l20l/cld2-cffi/**`

same here,  did you suceed to pip install ?

**Comment by vgrabovets** [comment]
See README:

If installation fails due to cld error narrowing conversions, than it can be installed with CFLAGS="-Wno-narrowing" pip install cld2-cffi and than pip install multi-rake

**Comment by lisabecker** [comment]
Trying to install multi-rake, I'm getting this error: 
`Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/bw/7dvpl8l11jl_mx7386rbkd300000gn/T/pip-install-221t47f9/cld2-cffi/`

When I'm running `CFLAGS="-Wno-narrowing" pip install cld2-cffi`, I'm getting another error: `Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/bw/7dvpl8l11jl_mx7386rbkd300000gn/T/pip-install-45ttwkqv/cld2-cffi/`

**Comment by vgrabovets** [comment]
Could you, please, post full traceback where actual error is mentioned?
`cld2-cffi` is written in C and needs to be compiled. Maybe, your machine doesn't have necessary files for the compiler.

**Comment by lisabecker** [comment]
Of course! I'm posting both tracebacks here:

**CFLAGS="-Wno-narrowing" pip install cld2-cffi:**

> (base) FoxBook:~ lisabecker$ CFLAGS="-Wno-narrowing" pip install cld2-cffi
> Collecting cld2-cffi
>   Using cached https://files.pythonhosted.org/packages/52/6d/044789e730141bcda2a7368836f714684a7d13bd44a2a33b387cb31b4335/cld2-cffi-0.1.4.tar.gz
>     Complete output from command python setup.py egg_info:
>     running egg_info
>     creating pip-egg-info/cld2_cffi.egg-info
>     writing pip-egg-info/cld2_cffi.egg-info/PKG-INFO
>     writing dependency_links to pip-egg-info/cld2_cffi.egg-info/dependency_links.txt
>     writing requirements to pip-egg-info/cld2_cffi.egg-info/requires.txt
>     writing top-level names to pip-egg-info/cld2_cffi.egg-info/top_level.txt
>     writing manifest file 'pip-egg-info/cld2_cffi.egg-info/SOURCES.txt'
>     In file included from cld2/__pycache__/_cffi__x8faeddebx1977d085.c:2:
>     /anaconda3/include/python3.6m/Python.h:25:10: fatal error: 'stdio.h' file not found
>     #include <stdio.h>
>              ^~~~~~~~~
>     1 error generated.
>     Traceback (most recent call last):
>       File "/anaconda3/lib/python3.6/distutils/unixccompiler.py", line 118, in _compile
>         extra_postargs)
>       File "/anaconda3/lib/python3.6/distutils/ccompiler.py", line 909, in spawn
>         spawn(cmd, dry_run=self.dry_run)
>       File "/anaconda3/lib/python3.6/distutils/spawn.py", line 36, in spawn
>         _spawn_posix(cmd, search_path, dry_run=dry_run)
>       File "/anaconda3/lib/python3.6/distutils/spawn.py", line 159, in _spawn_posix
>         % (cmd, exit_status))
>     distutils.errors.DistutilsExecError: command 'x86_64-apple-darwin13.4.0-clang' failed with exit status 1
>     
>     During handling of the above exception, another exception occurred:
>     
>     Traceback (most recent call last):
>       File "/anaconda3/lib/python3.6/site-packages/cffi/ffiplatform.py", line 51, in _build
>         dist.run_command('build_ext')
>       File "/anaconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
>         cmd_obj.run()
>       File "/anaconda3/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 78, in run
>         _build_ext.run(self)
>       File "/anaconda3/lib/python3.6/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
>         _build_ext.build_ext.run(self)
>       File "/anaconda3/lib/python3.6/distutils/command/build_ext.py", line 339, in run
>         self.build_extensions()
>       File "/anaconda3/lib/python3.6/site-packages/Cython/Distutils/old_build_ext.py", line 194, in build_extensions
>         self.build_extension(ext)
>       File "/anaconda3/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 199, in build_extension
>         _build_ext.build_extension(self, ext)
>       File "/anaconda3/lib/python3.6/distutils/command/build_ext.py", line 533, in build_extension
>         depends=ext.depends)
>       File "/anaconda3/lib/python3.6/distutils/ccompiler.py", line 574, in compile
>         self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
>       File "/anaconda3/lib/python3.6/distutils/unixccompiler.py", line 120, in _compile
>         raise CompileError(msg)
>     distutils.errors.CompileError: command 'x86_64-apple-darwin13.4.0-clang' failed with exit status 1
>     
>     During handling of the above exception, another exception occurred:
>     
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "/private/var/folders/bw/7dvpl8l11jl_mx7386rbkd300000gn/T/pip-install-0zxr63y7/cld2-cffi/setup.py", line 191, in <module>
>         'Topic :: Text Processing :: Linguistic'
>       File "/anaconda3/lib/python3.6/site-packages/setuptools/__init__.py", line 143, in setup
>         return distutils.core.setup(**attrs)
>       File "/anaconda3/lib/python3.6/distutils/core.py", line 148, in setup
>         dist.run_commands()
>       File "/anaconda3/lib/python3.6/distutils/dist.py", line 955, in run_commands
>         self.run_command(cmd)
>       File "/anaconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
>         cmd_obj.run()
>       File "/anaconda3/lib/python3.6/site-packages/setuptools/command/egg_info.py", line 296, in run
>         self.find_sources()
>       File "/anaconda3/lib/python3.6/site-packages/setuptools/command/egg_info.py", line 303, in find_sources
>         mm.run()
>       File "/anaconda3/lib/python3.6/site-packages/setuptools/command/egg_info.py", line 534, in run
>         self.add_defaults()
>       File "/anaconda3/lib/python3.6/site-packages/setuptools/command/egg_info.py", line 570, in add_defaults
>         sdist.add_defaults(self)
>       File "/anaconda3/lib/python3.6/site-packages/setuptools/command/py36compat.py", line 34, in add_defaults
>         self._add_defaults_python()
>       File "/anaconda3/lib/python3.6/site-packages/setuptools/command/sdist.py", line 127, in _add_defaults_python
>         build_py = self.get_finalized_command('build_py')
>       File "/anaconda3/lib/python3.6/distutils/cmd.py", line 299, in get_finalized_command
>         cmd_obj.ensure_finalized()
>       File "/anaconda3/lib/python3.6/distutils/cmd.py", line 107, in ensure_finalized
>         self.finalize_options()
>       File "/anaconda3/lib/python3.6/site-packages/setuptools/command/build_py.py", line 34, in finalize_options
>         orig.build_py.finalize_options(self)
>       File "/anaconda3/lib/python3.6/distutils/command/build_py.py", line 45, in finalize_options
>         ('force', 'force'))
>       File "/anaconda3/lib/python3.6/distutils/cmd.py", line 287, in set_undefined_options
>         src_cmd_obj.ensure_finalized()
>       File "/anaconda3/lib/python3.6/distutils/cmd.py", line 107, in ensure_finalized
>         self.finalize_options()
>       File "/private/var/folders/bw/7dvpl8l11jl_mx7386rbkd300000gn/T/pip-install-0zxr63y7/cld2-cffi/setup.py", line 143, in finalize_options
>         self.distribution.ext_modules = get_ext_modules()
>       File "/private/var/folders/bw/7dvpl8l11jl_mx7386rbkd300000gn/T/pip-install-0zxr63y7/cld2-cffi/setup.py", line 128, in get_ext_modules
>         import cld2
>       File "/private/var/folders/bw/7dvpl8l11jl_mx7386rbkd300000gn/T/pip-install-0zxr63y7/cld2-cffi/cld2/__init__.py", line 190, in <module>
>         extra_compile_args=_COMPILER_ARGS)
>       File "/anaconda3/lib/python3.6/site-packages/cffi/api.py", line 451, in verify
>         lib = self.verifier.load_library()
>       File "/anaconda3/lib/python3.6/site-packages/cffi/verifier.py", line 104, in load_library
>         self._compile_module()
>       File "/anaconda3/lib/python3.6/site-packages/cffi/verifier.py", line 201, in _compile_module
>         outputfilename = ffiplatform.compile(tmpdir, self.get_extension())
>       File "/anaconda3/lib/python3.6/site-packages/cffi/ffiplatform.py", line 22, in compile
>         outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
>       File "/anaconda3/lib/python3.6/site-packages/cffi/ffiplatform.py", line 58, in _build
>         raise VerificationError('%s: %s' % (e.__class__.__name__, e))
>     cffi.error.VerificationError: CompileError: command 'x86_64-apple-darwin13.4.0-clang' failed with exit status 1
>     
>     ----------------------------------------
> Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/bw/7dvpl8l11jl_mx7386rbkd300000gn/T/pip-install-0zxr63y7/cld2-cffi/

**pip install multi-rake:**

> (base) FoxBook:~ lisabecker$ pip install multi-rake
> Collecting multi-rake
>   Using cached https://files.pythonhosted.org/packages/5f/26/8d1fd22c5e1bf65936bae9f8201df2fa8cefe6fa0b28f471384e8101b298/multi_rake-0.0.1-py3-none-any.whl
> Requirement already satisfied: regex>=2018.6.6 in /anaconda3/lib/python3.6/site-packages (from multi-rake) (2018.11.22)
> Requirement already satisfied: numpy>=1.14.4 in /anaconda3/lib/python3.6/site-packages (from multi-rake) (1.15.4)
> Collecting cld2-cffi>=0.1.4 (from multi-rake)
>   Using cached https://files.pythonhosted.org/packages/52/6d/044789e730141bcda2a7368836f714684a7d13bd44a2a33b387cb31b4335/cld2-cffi-0.1.4.tar.gz
>     Complete output from command python setup.py egg_info:
>     running egg_info
>     creating pip-egg-info/cld2_cffi.egg-info
>     writing pip-egg-info/cld2_cffi.egg-info/PKG-INFO
>     writing dependency_links to pip-egg-info/cld2_cffi.egg-info/dependency_links.txt
>     writing requirements to pip-egg-info/cld2_cffi.egg-info/requires.txt
>     writing top-level names to pip-egg-info/cld2_cffi.egg-info/top_level.txt
>     writing manifest file 'pip-egg-info/cld2_cffi.egg-info/SOURCES.txt'
>     In file included from cld2/__pycache__/_cffi__x8faeddebx1977d085.c:2:
>     /anaconda3/include/python3.6m/Python.h:25:10: fatal error: 'stdio.h' file not found
>     #include <stdio.h>
>              ^~~~~~~~~
>     1 error generated.
>     Traceback (most recent call last):
>       File "/anaconda3/lib/python3.6/distutils/unixccompiler.py", line 118, in _compile
>         extra_postargs)
>       File "/anaconda3/lib/python3.6/distutils/ccompiler.py", line 909, in spawn
>         spawn(cmd, dry_run=self.dry_run)
>       File "/anaconda3/lib/python3.6/distutils/spawn.py", line 36, in spawn
>         _spawn_posix(cmd, search_path, dry_run=dry_run)
>       File "/anaconda3/lib/python3.6/distutils/spawn.py", line 159, in _spawn_posix
>         % (cmd, exit_status))
>     distutils.errors.DistutilsExecError: command 'x86_64-apple-darwin13.4.0-clang' failed with exit status 1
>     
>     During handling of the above exception, another exception occurred:
>     
>     Traceback (most recent call last):
>       File "/anaconda3/lib/python3.6/site-packages/cffi/ffiplatform.py", line 51, in _build
>         dist.run_command('build_ext')
>       File "/anaconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
>         cmd_obj.run()
>       File "/anaconda3/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 78, in run
>         _build_ext.run(self)
>       File "/anaconda3/lib/python3.6/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
>         _build_ext.build_ext.run(self)
>       File "/anaconda3/lib/python3.6/distutils/command/build_ext.py", line 339, in run
>         self.build_extensions()
>       File "/anaconda3/lib/python3.6/site-packages/Cython/Distutils/old_build_ext.py", line 194, in build_extensions
>         self.build_extension(ext)
>       File "/anaconda3/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 199, in build_extension
>         _build_ext.build_extension(self, ext)
>       File "/anaconda3/lib/python3.6/distutils/command/build_ext.py", line 533, in build_extension
>         depends=ext.depends)
>       File "/anaconda3/lib/python3.6/distutils/ccompiler.py", line 574, in compile
>         self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
>       File "/anaconda3/lib/python3.6/distutils/unixccompiler.py", line 120, in _compile
>         raise CompileError(msg)
>     distutils.errors.CompileError: command 'x86_64-apple-darwin13.4.0-clang' failed with exit status 1
>     
>     During handling of the above exception, another exception occurred:
>     
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "/private/var/folders/bw/7dvpl8l11jl_mx7386rbkd300000gn/T/pip-install-im1swfmi/cld2-cffi/setup.py", line 191, in <module>
>         'Topic :: Text Processing :: Linguistic'
>       File "/anaconda3/lib/python3.6/site-packages/setuptools/__init__.py", line 143, in setup
>         return distutils.core.setup(**attrs)
>       File "/anaconda3/lib/python3.6/distutils/core.py", line 148, in setup
>         dist.run_commands()
>       File "/anaconda3/lib/python3.6/distutils/dist.py", line 955, in run_commands
>         self.run_command(cmd)
>       File "/anaconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
>         cmd_obj.run()
>       File "/anaconda3/lib/python3.6/site-packages/setuptools/command/egg_info.py", line 296, in run
>         self.find_sources()
>       File "/anaconda3/lib/python3.6/site-packages/setuptools/command/egg_info.py", line 303, in find_sources
>         mm.run()
>       File "/anaconda3/lib/python3.6/site-packages/setuptools/command/egg_info.py", line 534, in run
>         self.add_defaults()
>       File "/anaconda3/lib/python3.6/site-packages/setuptools/command/egg_info.py", line 570, in add_defaults
>         sdist.add_defaults(self)
>       File "/anaconda3/lib/python3.6/site-packages/setuptools/command/py36compat.py", line 34, in add_defaults
>         self._add_defaults_python()
>       File "/anaconda3/lib/python3.6/site-packages/setuptools/command/sdist.py", line 127, in _add_defaults_python
>         build_py = self.get_finalized_command('build_py')
>       File "/anaconda3/lib/python3.6/distutils/cmd.py", line 299, in get_finalized_command
>         cmd_obj.ensure_finalized()
>       File "/anaconda3/lib/python3.6/distutils/cmd.py", line 107, in ensure_finalized
>         self.finalize_options()
>       File "/anaconda3/lib/python3.6/site-packages/setuptools/command/build_py.py", line 34, in finalize_options
>         orig.build_py.finalize_options(self)
>       File "/anaconda3/lib/python3.6/distutils/command/build_py.py", line 45, in finalize_options
>         ('force', 'force'))
>       File "/anaconda3/lib/python3.6/distutils/cmd.py", line 287, in set_undefined_options
>         src_cmd_obj.ensure_finalized()
>       File "/anaconda3/lib/python3.6/distutils/cmd.py", line 107, in ensure_finalized
>         self.finalize_options()
>       File "/private/var/folders/bw/7dvpl8l11jl_mx7386rbkd300000gn/T/pip-install-im1swfmi/cld2-cffi/setup.py", line 143, in finalize_options
>         self.distribution.ext_modules = get_ext_modules()
>       File "/private/var/folders/bw/7dvpl8l11jl_mx7386rbkd300000gn/T/pip-install-im1swfmi/cld2-cffi/setup.py", line 128, in get_ext_modules
>         import cld2
>       File "/private/var/folders/bw/7dvpl8l11jl_mx7386rbkd300000gn/T/pip-install-im1swfmi/cld2-cffi/cld2/__init__.py", line 190, in <module>
>         extra_compile_args=_COMPILER_ARGS)
>       File "/anaconda3/lib/python3.6/site-packages/cffi/api.py", line 451, in verify
>         lib = self.verifier.load_library()
>       File "/anaconda3/lib/python3.6/site-packages/cffi/verifier.py", line 104, in load_library
>         self._compile_module()
>       File "/anaconda3/lib/python3.6/site-packages/cffi/verifier.py", line 201, in _compile_module
>         outputfilename = ffiplatform.compile(tmpdir, self.get_extension())
>       File "/anaconda3/lib/python3.6/site-packages/cffi/ffiplatform.py", line 22, in compile
>         outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
>       File "/anaconda3/lib/python3.6/site-packages/cffi/ffiplatform.py", line 58, in _build
>         raise VerificationError('%s: %s' % (e.__class__.__name__, e))
>     cffi.error.VerificationError: CompileError: command 'x86_64-apple-darwin13.4.0-clang' failed with exit status 1
>     
>     ----------------------------------------
> Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/bw/7dvpl8l11jl_mx7386rbkd300000gn/T/pip-install-im1swfmi/cld2-cffi/

**Comment by vgrabovets** [comment]
So, the error is `'stdio.h' file not found`. It is C file needed to compile `cld2-cffi`.
[Here](https://stackoverflow.com/questions/22603195/fatal-error-include-stdio-h-generated-after-pip-install-mysql-python-comma) and [here](https://stackoverflow.com/questions/19580758/gcc-fatal-error-stdio-h-no-such-file-or-directory) it is suggested to run `xcode-select --install` before installation (macOS) or `sudo apt-get install libc6-dev` (Ubuntu).
Please, let me know if it solves the problem.

**Comment by vgrabovets** [comment]
@lisabecker Did my comment above solve your issue?

**Comment by lisabecker** [comment]
Thanks for the fast answer and suggestions! Unfortunately, it didn't work.` xcode-select --install` didn't work, it showed me that the "current version isn't available". So I first installed XCode from the Appstore, tried the `CFLAGS="-Wno-narrowing" pip install cld2-cffi` and `pip install multi-rake` again, but it gave me the same error codes. I deinstalled XCode and tried downloading XCode and Command Line Codes directly from https://developer.apple.com/download/more/, but I'm still getting the same error messages with `CFLAGS="-Wno-narrowing" pip install cld2-cffi` and `pip install multi-rake.

**Comment by pressure679** [comment]
copy paste into command prompt: "export CFLAGS="-Wno-narrowing"; pip install cld2-cffi; pip install multi-rake". The exported string/environment variable will only be in the command it is issued in and be cleared when the used command prompt/terminal app is closed.

Perhaps look at https://github.com/csurfer/rake-nltk instead, it looks similar to this - I am installing it now.
